version: '3.3'
services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    
  frontend:
    container_name: frontend
    build: ./frontend-react
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend