# Generated by Django 4.2 on 2024-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_refreshtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
